stages:
    - build
    - test
    - deploy
before_script:       
    - echo "Before script"    
building:
    stage: build
    only:
        - master
    tags:
        - rpm        
    variables:
        ENV_FILE: "$ENV_FILE"
        API_JS: "$API_JS"
    script:       
        - sudo rm -rf /mnt/storage/cicdapps/rpm
        - mkdir /mnt/storage/cicdapps/rpm
        - rsync -av --progress . /mnt/storage/cicdapps/rpm --exclude .git
        - cd /mnt/storage/cicdapps/rpm        
        - cp $ENV_FILE .env
        - composer install --ignore-platform-reqs
        - composer dump-autoload
        - rm /mnt/storage/cicdapps/rpm/resources/js/apis/Api.js        
        - cp $API_JS /mnt/storage/cicdapps/rpm/resources/js/apis/Api.js
        - php artisan cache:clear
        - php artisan key:generate
        - php artisan migrate:fresh --seed
        - npm update
        - npm run production
        - sudo chown -R www-data:www-data /mnt/storage/cicdapps/rpm/
        - sudo find /mnt/storage/cicdapps/rpm -type f -exec chmod 664 {} \;
        - sudo find /mnt/storage/cicdapps/rpm -type d -exec chmod 775 {} \;
        - sudo chmod -R 775 /mnt/storage/applications/rpm/storage/
        - sudo chgrp -R www-data storage bootstrap/cache
        - sudo chmod -R ug+rwx storage bootstrap/cache
testing:
    stage: test
    tags:
        - rpm        
    only:
        - master
    script:
        - cd /mnt/storage/cicdapps/rpm  
        - php artisan test
deploying:
    stage: deploy
    tags:
        - rpm
    only:
        - master
    script:
        - sudo rsync -av --progress /mnt/storage/cicdapps/rpm/* /mnt/storage/applications/rpm --exclude .env --exclude .gitlab-ci.yml --exclude .env.gitlab-ci --exclude .git --exclude .gitignore --exclude .gitattributes --exclude node_modules
        - cd /mnt/storage/applications/rpm
        # uncomment below line, if need to recreate and seed data again.
        - php artisan migrate:fresh --seed
        - php artisan optimize:clear